substitutions:
  _IMAGE: asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api
  _TAG: $SHORT_SHA   # Cloud Build が自動で入れる短いコミットSHA

steps:
  # 1⃣ Build & push
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_IMAGE:$_TAG', '.']

  # 2⃣ Deploy to Cloud Run (タグのみ)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    args:
      - run
      - deploy
      - rag-api
      - '--image=$_IMAGE:$_TAG'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=190389115361-compute@developer.gserviceaccount.com'

images:
  - '$_IMAGE:$_TAG'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
