substitutions:
  _IMAGE: asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api
  _TAG: $SHORT_SHA            # Git の短 SHA

steps:
  # 1️⃣ Build
  - name: gcr.io/cloud-builders/docker
    id: build
    args: ['build', '-t', '$_IMAGE:$_TAG', '.']

  # 2️⃣ Push  ←★追加
  - name: gcr.io/cloud-builders/docker
    id: push
    args: ['push', '$_IMAGE:$_TAG']

  # 3️⃣ Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    args:
      - gcloud
      - run
      - deploy
      - rag-api
      - '--image=$_IMAGE:$_TAG'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=190389115361-compute@developer.gserviceaccount.com'

images:
  - '$_IMAGE:$_TAG'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
