# ───────── Cloud Build config ─────────
# 変数 _TAG に自動で SHORT_SHA が入る
substitutions:
  _TAG: "$SHORT_SHA"

steps:
  # 1️⃣ Docker build & push
  - name: gcr.io/cloud-builders/docker
    env: ['PIP_DEFAULT_TIMEOUT=180']        # ← PyPI タイムアウト対策（任意）
    args:
      - build
      - -t
      - asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:${_TAG}
      - .

  # 2️⃣ Cloud Run deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - rag-api
      - --image=asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:${_TAG}
      - --region=asia-northeast1
      - --platform=managed
      - --allow-unauthenticated
      - --service-account=190389115361-compute@developer.gserviceaccount.com

# Cloud Build UI に表示される “ビルド済みイメージ” 情報
images:
  - asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:${_TAG}

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
