steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '--no-cache',
      '-t', 'asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:v1.0.99',
      '.'
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      'asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:v1.0.99'
    ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - rag-api
      - --image=asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:v1.0.99
      - --region=asia-northeast1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=16Gi
      - --cpu=4
      - --timeout=600s
      - --min-instances=1
      - --max-instances=20
      - --concurrency=80
      - --port=8080
      - --set-env-vars=MODEL_PRESET=auto,MAX_NEW_TOKENS=256,DB_HOST=10.19.80.4,DB_PORT=5432,DB_NAME=rag_db,DB_USER=raguser
      - --set-secrets=DB_PASSWORD=db-password:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_REDIRECT_URI=GOOGLE_REDIRECT_URI:latest
      - --service-account=190389115361-compute@developer.gserviceaccount.com
      - --vpc-connector=cloudrun-to-sql
      - --vpc-egress=private-ranges-only

images:
  - 'asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:v1.0.99'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
