steps:
  # APIサーバー用イメージのビルド＆プッシュ＆デプロイ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rag-api', './api']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rag-api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'rag-api',
      '--image', 'gcr.io/$PROJECT_ID/rag-api',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  # フロントエンド用イメージのビルド＆プッシュ＆デプロイ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rag-front', './front']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rag-front']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'rag-front',
      '--image', 'gcr.io/$PROJECT_ID/rag-front',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

timeout: '1200s'
