substitutions:
  _IMAGE: asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api
  _TAG: v1.0.0            # 固定のタグを使用

steps:
  # 1️⃣ Build
  - name: gcr.io/cloud-builders/docker
    id: build
    args: ['build', '-t', '$_IMAGE:$_TAG', '.']

  # 2️⃣ Push
  - name: gcr.io/cloud-builders/docker
    id: push
    args: ['push', '$_IMAGE:$_TAG']

  # 3️⃣ Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: 'gcloud'   # entrypointを明示的に指定
    args:
      - 'run'
      - 'deploy'
      - 'rag-api'
      - '--image=$_IMAGE:$_TAG'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'     # より多くのメモリを割り当て
      - '--cpu=2'          # 複数のCPUコアを割り当て
      - '--timeout=600s'   # 長めのタイムアウト設定
      - '--min-instances=1' # 常に1インスタンスをホット状態に保つ
      - '--max-instances=20' # 高負荷時に多くのインスタンスを許可
      - '--concurrency=80'  # 1インスタンスあたりの同時リクエスト数
      - '--service-account=190389115361-compute@developer.gserviceaccount.com'

images:
  - '$_IMAGE:$_TAG'

options:
  machineType: 'E2_HIGHCPU_8'  # 高性能なビルドマシン
  logging: CLOUD_LOGGING_ONLY