substitutions:
  _GIT_COMMIT_SHA: "main"
  _IMAGE_TAG: "$SHORT_SHA"

steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking out commit: ${_GIT_COMMIT_SHA}"
        git fetch --all
        git checkout ${_GIT_COMMIT_SHA}
    id: 'Checkout Source'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--no-cache',
      '-t', 'asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:${_IMAGE_TAG}',
      '-t', 'asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:latest',
      '.'
    ]
    waitFor: ['Checkout Source']
    id: 'Build Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:${_IMAGE_TAG}'
    ]
    waitFor: ['Build Docker Image']
    id: 'Push Dynamic Tag Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:latest'
    ]
    waitFor: ['Push Dynamic Tag Image']
    id: 'Push Latest Tag Image'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - rag-api
      - --image=asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:${_IMAGE_TAG}
      - --region=asia-northeast1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=16Gi
      - --cpu=4
      - --timeout=600s
      - --min-instances=1
      - --max-instances=20
      - --concurrency=80
      - --port=8080
      - --set-env-vars=MODEL_PRESET=auto,MAX_NEW_TOKENS=256,DB_HOST=10.19.80.4,DB_PORT=5432,DB_NAME=rag_db,DB_USER=raguser
      - --set-secrets=DB_PASSWORD=db-password:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_REDIRECT_URI=GOOGLE_REDIRECT_URI:latest
      - --service-account=190389115361-compute@developer.gserviceaccount.com
      - --vpc-connector=cloudrun-to-sql
      - --vpc-egress=private-ranges-only
      - --update-labels=gcb-commit-sha=${_GIT_COMMIT_SHA},image-tag=${_IMAGE_TAG}
    waitFor: ['Push Latest Tag Image']
    id: 'Deploy to Cloud Run'

images:
  - 'asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:${_IMAGE_TAG}'
  - 'asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
