substitutions:
  _IMAGE: asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api
  _TAG: $SHORT_SHA            # ← コミットの短縮 SHA

steps:
  # 1️⃣ Build & push
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_IMAGE:$_TAG', '.']

  # 2️⃣ Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: bash
    args:
      - -c
      - |
          IMG="$_IMAGE:$_TAG"
          DIGEST=$(gcloud artifacts docker images describe "$IMG" --format='value(image_summary.digest)')
          gcloud run deploy rag-api \
            --image="$IMG@$DIGEST" \
            --region=asia-northeast1 \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=190389115361-compute@developer.gserviceaccount.com

images:
  - '$_IMAGE:$_TAG'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
