steps:
  # 1. Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/rag-cloud-project/rag-api', '.']

  # 2. Cloud Run にデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'rag-api'
      - '--image=gcr.io/rag-cloud-project/rag-api'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/rag-cloud-project/rag-api'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # メモリ不足対策（必要に応じて E2_HIGHCPU_32 に変更）
