substitutions:
  _TAG: v1.0.0
  _IMAGE_NAME: asia-northeast1-docker.pkg.dev/rag-cloud-project/rag-chat-pro/rag-api
  _IMAGE_WITH_TAG: $_IMAGE_NAME:$_TAG

steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_IMAGE_WITH_TAG', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_IMAGE_WITH_TAG']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - rag-api
      - '--image=$_IMAGE_WITH_TAG'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--timeout=600s'
      - '--min-instances=1'
      - '--max-instances=20'
      - '--concurrency=80'
      - '--service-account=190389115361-compute@developer.gserviceaccount.com'

images:
  - '$_IMAGE_WITH_TAG'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY   # ← ✅ この行を追加！！


