# config/company.yaml
company: 秋山住研
name: キノエデザイン
address: 〒673-0404 兵庫県三木市平田120-1
phone: 0794-82-8540
email: support@aki-jyu.comまでメールをお送りください。
representative: 代表取締役 秋山 高利
revised: 2025-08-17
version: v1.0